name: mullr_components
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^2.3.2
  cloud_firestore: ^2.5.2
  crypto: ^3.0.1
  connectivity_plus: ^1.1.0
  device_info: ^2.0.2
  encrypt: ^5.0.1
  firebase_auth: ^3.1.1
  firebase_crashlytics: ^2.2.1
  firebase_messaging: ^10.0.4
  firebase_remote_config: ^0.10.0+3
  flex_color_picker: ^2.1.2
  #flutter_facebook_auth: ^3.5.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0
  gap: ^2.0.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  hive: ^2.0.4
  dart_jsonwebtoken: ^2.1.1
  local_auth: ^1.1.5
  mask_text_input_formatter: ^2.0.0
  package_info_plus: ^1.0.6
  pointycastle: ^3.0.1
  rsa_encrypt: ^2.0.0
  shared_preferences: ^2.0.7
  sign_in_with_apple: ^3.0.0
  stacked: ^2.2.5
  steel_crypt: ^3.0.0+1
  timeago: ^3.1.0
  url_launcher: ^6.0.10


  # Requires Android setup
  flutter_secure_storage: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.1
  hive_generator: ^1.0.1
  json_serializable: ^4.0.0


flutter:


