name: mullr_components
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^3.1.3
  cloud_firestore: ^3.1.1
  crypto: ^3.0.1
  connectivity_plus: ^2.1.0
  device_info_plus: ^3.1.1
  encrypt: ^5.0.1
  firebase_auth: ^3.3.0
  firebase_crashlytics: ^2.4.0
  firebase_messaging: ^11.2.0
  firebase_remote_config: ^0.11.0+2
  flex_color_picker: ^2.2.0
  #flutter_facebook_auth: ^3.5.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.2.0
  gap: ^2.0.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  hive: ^2.0.4
  dart_jsonwebtoken: ^2.1.1
  local_auth: ^1.1.5
  mask_text_input_formatter: ^2.0.0
  package_info_plus: ^1.3.0
  pointycastle: ^3.0.1
  rsa_encrypt: ^2.0.0
  shared_preferences: ^2.0.9
  sign_in_with_apple: ^3.3.0
  stacked: ^2.2.7+1
  steel_crypt: ^3.0.0+1
  timeago: ^3.1.0
  url_launcher: ^6.0.17


  # Requires Android setup
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.5
  hive_generator: ^1.1.1
  json_annotation: ^4.4.0


flutter:


