name: {{#snakeCase}}{{name}}{{/snakeCase}}
description: Post about all your different interests
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  algolia: ^1.0.1
  auto_route: ^2.4.1
  badges: ^2.0.1
  blurhash: ^1.0.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.3
  connectivity_plus: ^1.1.0
  detectable_text_field: ^2.0.3
  device_info_plus: ^2.1.0
  dots_indicator: ^2.0.0
  entry: ^0.0.6
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_dynamic_links: ^2.0.9
  flutter_blurhash: ^0.6.0
  flutter_hooks: ^0.18.0
  flutter_local_notifications: ^8.2.0
  firebase_messaging: ^10.0.8
  firebase_remote_config: ^0.10.0+5
  firebase_storage: ^10.0.1
  flutter_portal: ^0.4.0
  gap: ^2.0.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_mobile_ads: ^0.13.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4
  infinite_scroll_pagination: ^3.1.0
  injectable: ^1.5.0
  json_serializable: ^5.0.2
  mullr_components:
    path: ../mullr_components
  octo_image: ^1.0.0+1
  share_plus: ^2.1.4
  simple_animations: ^4.0.0
  sliver_tools: ^0.2.5
  stacked: ^2.2.5
  transparent_image: ^2.0.0
  url_launcher: ^6.0.3
  universal_io: ^2.0.4
  wiredash: ^0.7.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^2.4.1
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.0
  injectable_generator: ^1.3.0
  json_annotation: ^4.1.0

# flutter pub run flutter_launcher_icons:main
#flutter_icons:
 # android: "launcher_icon"
  #ios: true
  #image_path: "assets/images/logo.png"
  #remove_alpha_ios: true

# flutter pub run flutter_native_splash:create
#flutter_native_splash:
 # color: "#ffffff"
  #image: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
   # - assets/images/
